# Generated by Django 4.2.5 on 2023-09-07 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestProcess',
            fields=[
                ('process_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HarvestStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='HarvestWebDirect',
            fields=[
                ('web_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('web_address', models.URLField()),
                ('collected_timestamp', models.DateTimeField(auto_now_add=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps_harvester.harvestprocess')),
            ],
        ),
        migrations.AddField(
            model_name='harvestprocess',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ps_harvester.harveststatus'),
        ),
        migrations.CreateModel(
            name='HarvestFile',
            fields=[
                ('file_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('filepath', models.FileField(editable=False, upload_to='')),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps_harvester.harvestprocess')),
            ],
        ),
        migrations.CreateModel(
            name='HarvestEntrySpeech',
            fields=[
                ('entry_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('speech_id', models.BigIntegerField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps_harvester.harvestprocess')),
            ],
        ),
    ]
