# Generated by Django 4.2.5 on 2023-09-29 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ps_harvester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestentryspeech',
            name='review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='harvestentryspeech',
            name='review_message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='harvestprocess',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='ps_harvester.harveststatus'),
        ),
    ]
